# Generated by Django 3.2.9 on 2021-11-28 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('riders', '0001_initial'),
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'NEW'), ('accepted', 'ACCEPTED'), ('picking_up', 'PICKING_UP'), ('reached_pickup', 'REACHED_PICKUP'), ('started_ride', 'STARTED_RIDE'), ('dropping_off', 'DROPPING_OFF'), ('reached_dropoff', 'REACHED_DROPOFF'), ('cancelled', 'CANCELLED'), ('completed', 'COMPLETED')], default='new', max_length=15)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides', to='drivers.driver')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides', to='riders.rider')),
            ],
        ),
    ]
